export interface Album {
  id: string;
  slug: string;
  title: string;
  artist: string;
  subtitle: string;
  description?: string;
  badge: string;
  coverUrl: string;
  themeColor: string;
  secondaryColor?: string;
  gradient?: string;
  program: 'Latin' | 'Standard' | 'Both';
  allowedStyles: string[];
  tags: string[];
  orderIndex: number;
  isPublished?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export const DEFAULT_ALBUMS: Album[] = [
  {
    id: 'album-georgie-musheev',
    slug: 'georgie-musheev',
    title: 'Georgie Musheev & 7 Winds',
    artist: 'Georgie Musheev & 7 Winds',
    subtitle: 'Exclusive Live Latin Dance Music. Dedicated Latin Final Mode practice with live band sounds.',
    description: 'Exclusive Live Latin Dance Music. Dedicated Latin Final Mode practice with live band sounds.',
    badge: 'LIVE SOUNDS COLLECTION',
    coverUrl: '/georgie-musheev.jpg',
    themeColor: '#e11d48',
    secondaryColor: '#be123c',
    gradient: 'linear-gradient(90deg, #e11d48, #be123c)',
    program: 'Latin',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive'],
    tags: ['musheev', '7 winds', 'seven winds', 'georgie musheev'],
    orderIndex: 0,
    isPublished: true,
  },
  {
    id: 'album-boris-myagkov',
    slug: 'boris-myagkov',
    title: 'Boris Myagkov Big Band',
    artist: 'Boris Myagkov Big Band',
    subtitle: 'Legendary Big Band Dance Music. Isolated collection with dedicated Latin & Standard Final Mode practice.',
    description: 'Legendary Big Band Dance Music. Isolated collection with dedicated Latin & Standard Final Mode practice.',
    badge: 'LIVE SOUNDS COLLECTION',
    coverUrl: '/boris-myagkov-big-band.jpg',
    themeColor: '#f59e0b',
    secondaryColor: '#d97706',
    gradient: 'linear-gradient(90deg, #f59e0b, #d97706)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ['boris myagkov', 'myagkov'],
    orderIndex: 1,
    isPublished: true,
  },
  {
    id: 'album-roses-band',
    slug: 'roses-band',
    title: "Rose's Band",
    artist: "Rose's Band",
    subtitle: 'Exclusive Live Dance Band Sounds. Isolated collection with dedicated Latin & Standard Final Mode practice.',
    description: 'Exclusive Live Dance Band Sounds. Isolated collection with dedicated Latin & Standard Final Mode practice.',
    badge: 'LIVE SOUNDS COLLECTION',
    coverUrl: '/rosesband.jpg',
    themeColor: '#22c55e',
    secondaryColor: '#10b981',
    gradient: 'linear-gradient(90deg, #22c55e, #10b981)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ["rose's band", 'roses band', 'rosesband'],
    orderIndex: 2,
    isPublished: true,
  },
  {
    id: 'album-dance-star-band',
    slug: 'dance-star-band',
    title: 'Dance Star Band',
    artist: 'Dance Star Band',
    subtitle: 'Exclusive Live Dance Band Sounds. Isolated collection with dedicated Latin & Standard Final Mode practice.',
    description: 'Exclusive Live Dance Band Sounds. Isolated collection with dedicated Latin & Standard Final Mode practice.',
    badge: 'LIVE SOUNDS COLLECTION',
    coverUrl: '/dancestar.jpg',
    themeColor: '#d946ef',
    secondaryColor: '#8b5cf6',
    gradient: 'linear-gradient(90deg, #d946ef, #8b5cf6)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ['dance star band', 'dance star', 'dancestar'],
    orderIndex: 3,
    isPublished: true,
  },
  {
    id: 'album-goc-2026',
    slug: 'goc-2026',
    title: 'GOC Final 2026 Music',
    artist: 'German Open Championship',
    subtitle: 'Exclusive German Open Championship finals music. Isolated collection with dedicated Latin & Standard Final Mode practice.',
    description: 'Exclusive German Open Championship finals music. Isolated collection with dedicated Latin & Standard Final Mode practice.',
    badge: 'SPECIAL COLLECTION',
    coverUrl: '/goc2026.png',
    themeColor: '#eab308',
    secondaryColor: '#ca8a04',
    gradient: 'linear-gradient(90deg, #eab308, #ca8a04)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ['goc 2026', 'goc', 'stuttgart'],
    orderIndex: 4,
    isPublished: true,
  },
  {
    id: 'album-dj-maksy',
    slug: 'dj-maksy',
    title: 'DJ Maksy Playlist',
    artist: 'DJ Maksy',
    subtitle: 'Top DanceSport Hits & Remixes by DJ Maksy. Professional ballroom music collection.',
    description: 'Top DanceSport Hits & Remixes by DJ Maksy. Professional ballroom music collection.',
    badge: 'DJ COLLECTION',
    coverUrl: '/dj-maksy.jpg',
    themeColor: '#3b82f6',
    secondaryColor: '#2563eb',
    gradient: 'linear-gradient(90deg, #3b82f6, #2563eb)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ['dj maksy', 'maksy'],
    orderIndex: 5,
    isPublished: true,
  },
  {
    id: 'album-midland-big-band',
    slug: 'midland-big-band',
    title: 'The Midland Big Band',
    artist: 'The Midland Big Band',
    subtitle: 'World Cup Favourites by The Midland Big Band. Classic big band ballroom music.',
    description: 'World Cup Favourites by The Midland Big Band. Classic big band ballroom music.',
    badge: 'BIG BAND COLLECTION',
    coverUrl: '/midland-big-band.jpg',
    themeColor: '#8b5cf6',
    secondaryColor: '#7c3aed',
    gradient: 'linear-gradient(90deg, #8b5cf6, #7c3aed)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ['midland', 'midland big band', 'the midland big band'],
    orderIndex: 6,
    isPublished: true,
  },
  {
    id: 'album-len-phillips',
    slug: 'len-phillips',
    title: 'The Len Phillips Big Band',
    artist: 'The Len Phillips Big Band',
    subtitle: 'Let\'s Face The Music And Dance. Classic Big Band Ballroom & Latin Music.',
    description: 'Let\'s Face The Music And Dance. Classic Big Band Ballroom & Latin Music.',
    badge: 'BIG BAND COLLECTION',
    coverUrl: '/len-phillips-big-band.jpg',
    themeColor: '#8b5cf6',
    secondaryColor: '#6d28d9',
    gradient: 'linear-gradient(90deg, #8b5cf6, #6d28d9)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ['len phillips', 'len phillips big band', 'lpbb', 'lets face the music'],
    orderIndex: 7,
    isPublished: true,
  },
  {
    id: 'album-empress-orchestra',
    slug: 'empress-orchestra',
    title: 'Empress Orchestra',
    artist: 'Empress Orchestra',
    subtitle: 'Official Blackpool Dance Festival Sounds. World Famous Ballroom Orchestra.',
    description: 'Official Blackpool Dance Festival Sounds. World Famous Ballroom Orchestra.',
    badge: 'ORCHESTRA COLLECTION',
    coverUrl: '/empress-orchestra.jpg',
    themeColor: '#a855f7',
    secondaryColor: '#7e22ce',
    gradient: 'linear-gradient(90deg, #a855f7, #7e22ce)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ['empress orchestra', 'the empress orchestra', 'empress orchestra big band'],
    orderIndex: 8,
    isPublished: true,
  },
  {
    id: 'album-la-grande-orchestra-italiana',
    slug: 'la-grande-orchestra-italiana',
    title: 'La Grande Orchestra Italiana',
    artist: 'La Grande Orchestra Italiana',
    subtitle: 'Italian Big Band Ballroom Favorites. Professional Dance Music Collection.',
    description: 'Italian Big Band Ballroom Favorites. Professional Dance Music Collection.',
    badge: 'ORCHESTRA COLLECTION',
    coverUrl: '/la-grande-orchestra-italiana.jpg',
    themeColor: '#ef4444',
    secondaryColor: '#dc2626',
    gradient: 'linear-gradient(90deg, #ef4444, #dc2626)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    tags: ['la grande orchestra italiana', 'la grande', 'orchestra italiana', 'goi', 'la grande orchestra'],
    orderIndex: 9,
    isPublished: true,
  },
  {
    id: 'album-4andone-mix',
    slug: '4andone-mix',
    title: '4ANDONE Mix',
    artist: '4ANDONE Music',
    subtitle: 'Exclusive 4ANDONE Studio Selection & Remixes for Ballroom & Latin Practice.',
    description: 'Exclusive 4ANDONE Studio Selection & Remixes for Ballroom & Latin Practice.',
    badge: 'STUDIO COLLECTION',
    coverUrl: '/4andone-mix.jpg',
    themeColor: '#10b981',
    secondaryColor: '#059669',
    gradient: 'linear-gradient(90deg, #10b981, #059669)',
    program: 'Both',
    allowedStyles: ['Samba', 'Cha-Cha-Cha', 'Rumba', 'Paso Doble', 'Jive', 'Slow Waltz', 'Tango', 'Viennese Waltz', 'Slow Foxtrot', 'Quickstep'],
    // No generic tags like 'mix' — 200+ tracks of every band carry it
    tags: ['4andone mix', '4and.one mix'],
    orderIndex: 10,
    isPublished: true,
  },
];

